[editor.colors]
default_font_color = 0xa6978aff
whitespace = 0x30300ff
carriage_return = 0x30300ff
search_result = 0x49483eff
selection_color = 0x9fff2e
token_match = 0xd95b5bff
active_line_number = 0x8a8592ff
inactive_line_number = 0x444248ff
line_number_sep = 0x8a8592ff
line_ruler = 0x8a8592ff
cursor = 0x6bdb85ff
tray = 0xa6978aff
need_save = 0xff0000ff
background = 0x1e1e1eff
warning = 0xe3811cff
error = 0xff0000ff
auto_line_ending = 0xff00ff
vim_cursor_color = 0x6bdb85ff
async_highlight = 0x446ccc47
selected_editor = 0x1e1e1eff
line_guides = 0xadd6ff26
active_line_guide = 0xd95b5bff
highlight_line_copy = 0x9a02ff
highlight_line_edit =  0x60b373ff
cursor_line_outline = 0x76767650
cursor_line_fill = 0x44424850

[editor.state]
show_line_numbers = false
auto_syntax_highlighting = true
auto_line_endings = true
render_whitespace = false
tabs_as_spaces = true
spellcheck_by_default = false
disable_line_highlight = false
html_copy_background = true
vim_mode = true
suppress_async_search = false
suppress_threaded_search = false
suppress_suggestions = false
modulate_color_glyphs = false
embold_vim_cursor = true
embold_cursor = false
line_guides = true
relative_numbering = false
clear_find = false
return_accept_suggestion = true
show_line_rulers = false
enable_active_line_fill = false
noisy_parse = false
noisy_search = false
noisy_events = false
noisy_flattened_events = false
noisy_find_all = false
font_size_px = 16
tray_font_size = 16
tabstop = 4
line_number_style = 'LineNumberStyle_Classic'
line_rulers = []

[[editor.highlights]]
color = 0xd8a51dff
tags = ['keyword.directive',
'keyword.directive.define',
'keyword.directive.include',
'macro.function',
'macro.define',
'macro.definition']

[[editor.highlights]]
color = 0xd95b5bff
tags = ['keyword.alloc',
'keyword.return',
'keyword.repeat',
'keyword.conditional',
'keyword.conditional.ternary',
'keyword.exception',
'keyword.coroutine',
'keyword.coroutine.return']

[[editor.highlights]]
color = 0x56a69cff
tags = ['keyword',
'keyword.operator',
'keyword.storage',
'boolean',
'function.builtin',
'type.builtin',
'type.qualifier',
'tag']

[[editor.highlights]]
color = 0x569cd6ff
tags = ['variable.builtin']

[[editor.highlights]]
color = 0x60b373ff
tags = ['function']

[[editor.highlights]]
color = 0x60b373ff
tags = ['function.call']

[[editor.highlights]]
color = 0x60b373ff
tags = ['function.method',
'function.method.call']

[[editor.highlights]]
color = 0x56a69cff
tags = ['type',
'property']

[[editor.highlights]]
color = 0x56a69cff
tags = ['attribute']

[[editor.highlights]]
color = 0xbfbfbfff
tags = ['constant',
'constant.builtin',
'number']

[[editor.highlights]]
color = 0xbfbfbfff
tags = ['string',
'string.escape',
'character']

[[editor.highlights]]
color = 0x7d7d7dff
tags = ['comment']

[[editor.highlights]]
color = 0xd95b5bff
tags = ['operator']

[[editor.highlights]]
color = 0xd95b5bff
tags = ['scope.name']

[[editor.highlights]]
color = 0x56a69cff
tags = ['embedded']

[diff.colors]
del = 0xff0000ff
ins = 0xff00ff
eq = 0xfaf5f5ff
trimmed_text = 0xe3811cff
graph_link = 0xbd42b7ff
selected_node_color = 0xed8212aa
last_save_node_color = 0xff00ff
external_change_node_color = 0xb11be3ff

[diff.state]
diff_font_size = 16

[file_explorer.colors]
default_font_color = 0x92e99aff
relative_dir_font_color = 0x6b7078ff
actively_rooted = 0xb23c78ff
background = 0x1e1e1eff
selection_color = 0x7e8081aa
match_color = 0xed8212aa
directory_color = 0x6037c8ff
unknown_color = 0xff0000ff
B_color = 0xffffffff
KB_color = 0x64dbeaff
MB_color = 0x9627d8ff
GB_color = 0xcd3256ff
TB_color = 0xd9b026ff
PB_color = 0xff0a00ff
EB_color = 0xffffffff

[file_explorer.state]
font_size = 16
noisy_dir_root = false
rooted_filters = ""

[feed.colors]
info = 0xccccccff
warning = 0xe3811cff
error = 0xff0000ff

[feed.state]
feed_font_size = 16

[widget.colors]
window_border = 0x313131ff
window_title_background = 0xadd6ff26
window_title_font_color = 0xa6978aff
window_close_button_hover = 0xf44747ff
window_close_button_pressed = 0xcd1010ff
scrollbar_inactive = 0xa1a1a100
scrollbar_active = 0xcbcbcb50
scrollbar_track_outline = 0xadd6ff26
custom_hotkey_fill = 0x49ff31
drag_drop_zone = 0xadd6ffff
outline_selection = 0x41774cff
warning = 0xe3811cff
error = 0xff0000ff
active_button = 0x1a70abff
loading_bar_progress = 0x98ff80
loading_bar_complete = 0x9a0280
active_tab_highlight = 0xffffff80
active_selection = 0x929292ff

[widget.state]
window_title_font_size = 16
scrollbar_width = 10
scrollbar_min_size = 20

[system.core]
preferred_file_explorer = ''
core_window_rect = [270, 208, 1366, 768]
async_update_frequency_ms = 1000
editor_theme = 'ColorTheme_Fred'
fullscreen = true
maximized = false
disable_sessions = false
noisy_session_info = false

[system.fonts]
fallback_fonts_folder = 'C:\Users\user\AppData\Local\Microsoft\Windows\Fonts\'
current_font = 'JetBrainsMonoNerdFontRegular'

[system.effects]
audio_keystroke = []
audio_return = []
postprocessing_enabled = true
screen_warp = true
multipass_crt = true
mute_audio = true
suppress_audio_startup = true
crt_mode = false
animate_cursor = true
light_mode = false
smooth_scroll = true
highlight_line_copy = true
highlight_line_edit = true
subpixel_font_aa = false

[hotkey.state]
hotkeys = 'C:\Users\user\AppData\Roaming\cadacama\fred\hotkeys.toml'

[plugins.core]
plugins_source_file = ''
gen_base_template_only = false
